version: 2
jobs:
  build:
    working_directory: ~/interlligence
    docker:
      - image: circleci/python:2.7.13
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: circle_test
          MYSQL_USER: root
          MYSQL_HOST: ubuntu
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: ubuntu
    steps:
      - checkout

          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          command: |
            cp tests/test_local_setting.py intelligence/local_settings.py

      - run:
          command: |
            sudo pip install -r requirements.txt
            sudo mkdir -p /var/log/interlligence/
            sudo chmod +777 /var/log/interlligence/
            python manage.py test tests
      - store_artifacts:
          path: test-reports/
          destination: tr1


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test